name: Django Migration Guy Action
description: Fixes conflicting Django migrations.
inputs:
  apps_path:
    description: Path of Django apps in your repository.
    required: false
    default: "."
  strategy:
    type: choice
    description: Create a PR with changes or push to current branch.
    options: 
    - create_pr
    - push
    default: create_pr
runs:
  using: composite
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: poetry
    - name: Install requirements
      run: poetry install --without dev --no-root
      shell: bash
    - name: Pass inputs to shell
      run: echo "APPS_PATH=${{ inputs.apps_path }}" >> $GITHUB_ENV
      shell: bash
    - name: Fix migrations
      id: fix-migrations
      run: poetry run python src/main.py
      shell: bash
    - name: Create pull request
      if:  ${{ inputs.strategy == 'create_pr' }} 
      uses: peter-evans/create-pull-request@v4
    - name: Commit changes
      if:  ${{ inputs.strategy == 'push' }} 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic Django migration merge
        commit_user_name: Django Migration Guy
        commit_user_email: not-a-person@web.com