name: Django Migration Guy Action
description: A GitHub action to automatically fix multiple leaf errors of Django migrations.
author: ulasozguler
branding:
  icon: 'align-center'
  color: 'yellow'
inputs:
  apps_path:
    description: Path of Django apps in your repository.
    required: false
    default: "."
  strategy:
    type: choice
    description: Fix Strategy
    options: 
    - create_pr
    - push
    default: create_pr
  labels:
    description: A comma separated list of labels for pull request.
    default: auto-migration
runs:
  using: composite
  steps:
    - name: asd
      shell: bash
      run: ls -lah /home/runner/work/_actions/ulasozguler/django-migration-guy/develop
    - name: Dump GitHub context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      shell: bash
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      shell: bash
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      shell: bash
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      shell: bash
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      shell: bash
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Show default environment variables
      shell: bash
      run: |
        echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
        echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
        echo "The run id is: $GITHUB_RUN_ID"
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"
        echo "GitHub SHA: $GITHUB_SHA"
    - name: list all
      shell: bash
      run: ls -lah && pwd
    - name: Install poetry
      run: pipx install poetry
      shell: bash
      working-directory: ${{github.action_path}}
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: poetry
      working-directory: ${{github.action_path}}
    - name: Install requirements
      run: poetry install --without dev --no-root
      shell: bash
      working-directory: ${{github.action_path}}
    - name: Pass inputs to shell
      run: echo "APPS_PATH=${{github.workspace}}/${{ inputs.apps_path }}" >> $GITHUB_ENV
      shell: bash
    - name: Fix migrations
      id: fix-migrations
      run: poetry run python src/main.py
      shell: bash
      working-directory: ${{github.action_path}}
    - name: Create pull request
      if:  ${{ inputs.strategy == 'create_pr' }} 
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Automatic Django migration merge
        committer: Django Migration Guy <not-a-person@web.com>
        title: Automatic Django migration merge
        body: ${{ steps.fix-migrations.outputs.pr_message }}
        delete-branch: true
        branch: auto/django-mig-merge
        labels: ${{ inputs.labels }}
        reviewers: ${{ github.actor }}
      working-directory: ${{github.action_path}}
    - name: Commit changes
      if:  ${{ inputs.strategy == 'push' }} 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic Django migration merge
        commit_user_name: Django Migration Guy
        commit_user_email: not-a-person@web.com
      working-directory: ${{github.action_path}}