name: 'Django Migration Guy Action'
description: 'Fixes conflicting Django migrations.'
inputs:
  apps_path:
    description: 'Path of Django apps in your repository.'
    required: true
    default: "."
runs:
  using: 'composite'
  steps:
    - name: Install poetry
      run: pipx install poetry
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install requirements
      run: poetry install --without dev --no-root
    - name: Pass Inputs to Shell
      run: |
            echo "APPS_PATH=${{ inputs.apps_path }}" >> $GITHUB_ENV
    - name: Fix migrations
      id: fix-migrations
      run: python src/main.py