name: 'Django Migration Guy Action'
description: 'Fixes conflicting Django migrations.'
inputs:
  apps_path:
    description: 'Path of Django apps in your repository.'
    required: false
    default: "."
runs:
  using: 'composite'
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install requirements
      run: poetry install --without dev --no-root
      shell: bash
    - name: Pass Inputs to Shell
      run: |
            echo "APPS_PATH=${{ inputs.apps_path }}" >> $GITHUB_ENV
      shell: bash
    - name: Fix migrations
      id: fix-migrations
      run: poetry run python src/main.py
      shell: bash
    - name: check status
      run: git status
      shell: bash
    - name: Check changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    - name: Commit changes
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic Django migration merge
        commit_user_name: Django Migration Guy