# Generated by Django 3.0 on 2023-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("someapp", "0002_question_new_field copy"),
    ]
