on:
  workflow_dispatch:
    inputs:
      apps_path:
        description: 'Apps path'
        required: true
        default: '.'
      strategy:
        type: choice
        description: Create a PR with changes or push to current branch.
        options: 
        - create_pr
        - push
        default: create_pr
jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          apps_path: ${{ github.event.inputs.apps_path }}
