on:
  workflow_dispatch:
    inputs:
      apps_path:
        description: 'Apps path'
        required: true
        default: '.'
      strategy:
        type: choice
        description: Fix Strategy
        options: 
        - create_pr
        - push
        default: create_pr
jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          apps_path: ${{ inputs.apps_path }}
          strategy: ${{ inputs.strategy }}
